site_name: Hetul Patel
theme:
  name: material
  logo: assets/icons8-code-64.png
  palette:
    primary: white
  features:
    - content.code.copy
  # font:
  #   text: Roboto Mono
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences      
  - admonition
nav:
  - index.md
  - experience.md
  - Blogs:
    - blogs/software_development_essentials.md
  - Projects:
    - projects/clothes_retrieval.md
    - projects/deep_face_recognition.md
    - projects/alpr.md
    - projects/on_device_classification.md
    - projects/auto_adaptive.md
    - projects/mind_controlled_home_automation.md
    - projects/hyperspectral_image_classification.md
    - projects/lecture_notes_saving_app.md
    - projects/3d_password.md
    - projects/spry.md
    - projects/mobile_app_for_visually_impaired.md
  - talks.md
  - publications.md
  - education.md
  - contact.md
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css  
extra:
  generator: false