site_name: Hetul Patel
theme:
  name: material
  logo: assets/icons8-code-64.png
  palette:
    primary: white
  font:
    text: Roboto Mono
markdown_extensions:
  - toc:
      permalink: true
nav:
  - index.md
  - experience.md
  - education.md
  - contact.md
extra_css:
  - stylesheets/extra.css  